AWSTemplateFormatVersion: '2010-09-09'
Description: Creation of S3 Bucket
Parameters:
  BucketName:
    Type: String
    Default: test-bucket-27july2021-4
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: BucketName
Outputs:
  S3IdOut:
    Description: Output of the S3 Bucket
    Value:
      Ref: MyS3Bucket
